server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.40:3307/game_user
    username: root
    password: ok
  activemq:
    broker-url: tcp://192.168.1.40:61616
mybatis:
  mapper-locations: mapper/*Mapper.xml
dubbo:
  application:
    name: game-user
  registry:
    address: 192.168.1.40:2181
    protocol: zookeeper
  protocol:
    port: -1
    name: dubbo