server:
  port: 8071

spring:
  activemq:
    broker-url: tcp://192.168.1.40:61616
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.40:3307/game_pay
    username: root
    password: ok

dubbo:
  application:
    name: game-pay
  registry:
    address: 192.168.1.40:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

mybatis:
  mapper-locations: mapper/*.xml