server:
  port: 8082

dubbo:
  application:
    name: qg-goods
  registry:
    address: 192.168.1.40:2181
    protocol: zookeeper
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
mybatis:
  mapper-locations: mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.40:3307/qg_goods
    username: root
    password: ok